name: versant_event
description: "vrsant event ."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.2+37

environment:
  sdk: ">=3.5.0 <4.0.0"
  #sdk: '^3.9.0'


dependencies:
  image_picker: ^1.0.7
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0 #new
  shared_preferences: ^2.2.0   #new
  ionicons: ^0.2.2
  intl: ^0.18.1
  docx_template:
    path: ./docx_template
  path_provider: ^2.1.0
  signature: ^5.4.0
  open_filex: ^4.5.0
  share_plus: ^10.0.0
  url_launcher: ^6.3.1
  pdf: ^3.11.1
  printing: ^5.14.2
  flutter_email_sender: 8.0.0
  msal_flutter: ^2.0.1
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  sqflite: ^2.4.2
  path: ^1.9.1
#dependency_overrides:
 # docx_template:
  #  path: ./docx_template

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/template_ve.docx
    - assets/logo.png
    - assets/footer.png
    - assets/logoVE.png


